# Generated by Django 4.2.16 on 2024-09-12 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Event_GRO_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('sitting_position_field', models.CharField(max_length=100)),
                ('invited_for_luncheon', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('sitting_position_luncheon', models.CharField(blank=True, max_length=100, null=True)),
                ('company_organization_department_ministry', models.CharField(max_length=255)),
                ('in_care_of', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('field_card_printed', models.BooleanField(default=False)),
                ('field_card_printed_date', models.DateTimeField(blank=True, null=True)),
                ('luncheon_card_printed', models.BooleanField(default=False)),
                ('luncheon_card_printed_date', models.DateTimeField(blank=True, null=True)),
                ('dispatched', models.BooleanField(default=False)),
                ('date_dispatched', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitees_created', to=settings.AUTH_USER_MODEL)),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatchers', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event_GRO_app.event')),
                ('field_card_printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_card_printers', to=settings.AUTH_USER_MODEL)),
                ('luncheon_card_printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='luncheon_card_printers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
