# Generated by Django 4.2.16 on 2024-09-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_GRO_app', '0002_invitee'),
    ]

    operations = [
        migrations.CreateModel(
            name='SittingFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sitting_types', models.JSONField()),
            ],
        ),
    ]
