# Generated by Django 4.2.16 on 2024-09-12 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Event_GRO_app', '0003_sittingformat'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type_of_sitting_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SittingFormat', to='Event_GRO_app.sittingformat'),
        ),
    ]
